spring:
    web:
        locale-resolver: fixed
        locale: pt_BR

    # Rabbit MQ server properties
    rabbitmq:
        host : localhost
        port: 5672
        username: guest
        password: guest

    data:
        mongodb:
            uri:  "mongodb+srv://vinicius:jUa5m742S!s#_uK@msnotification.cyhutko.mongodb.net/?retryWrites=true&w=majority&appName=msnotification"
            port: 27017
            database: msnotification

server:
    port : 9090

rabbitmq:
    queue:
        name: ms_notification
    exchange:
        name: ms_notification_exchange
    routing:
        key: ms_notification_routing_key
