spring:
    web:
        locale-resolver: fixed
        locale: pt_BR

    # MYSQL
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/msnotification?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo
        username: root
        password:

    # JPA
    jpa:
        show-sql: true
        properties:
            hibernate.format_sql: false
        hibernate:
            ddl-auto: update
    # Rabbit MQ server properties
    rabbitmq:
        host : localhost
        port: 5672
        username: guest
        password: guest
server:
    port : 9090

rabbitmq:
    queue:
        name: ms_notification
    exchange:
        name: ms_notification_exchange
    routing:
        key: ms_notification_routing_key
